all_extension ={
    #other
    'other' : 'Others',
    #audio
    '.mp3' : 'Audio/',
    '.cda' : 'Audio/',
    '.mid' : 'Audio/',
    '.midi' : 'Audio/',
    'ogg' : 'Audio/',
    '.wav' : 'Audio/',
    'wma' : 'Audio/',
    'wpl' : 'Audio/',
    #image
    '.png' : 'Images/',
    '.ai' : 'Images/',
    '.gif' : 'Images/',
    '.ico' : 'Images/',
    '.jpeg' : 'Images/',
    '.jpg' : 'Images/',
    '.psd' : 'Images/',
    '.svg' : 'Images/',
    '.tif' : 'Images/',
    '.bmp' : 'Images/',
    #zip
    '.7z' : 'ZipFiles/',
    '.arj' : 'ZipFiles/',
    '.deb' : 'ZipFile/',
    '.pkg' : 'ZipFiles/',
    '.rar' : 'ZipFiles/',
    '.rpm' : 'ZipFiles/',
    '.tar.gz' : 'ZipFiles/',
    '.z' : 'ZipFiles/',
    '.zip' : 'ZipFiles/',
    #executable
    '.apk' : 'Executable/',
    '.bat' : 'Executable/',
    '.bin' : 'Executable/',
    '.com' : 'Executable/',
    '.exe' : 'Executable/',
    '.jar' : 'Executable/',
    '.gadget' : 'Executable/',
    '.msi' : 'Executable/',
    '.wsf' : 'Executable/',
    '.cgi' : 'Executable/',
    #microsoft
    '.ppt' : 'Microsoft/',
    '.pptx' : 'Microsoft/',
    '.pps' : 'Microsoft/',
    '.xls' : 'Microsoft/',
    '.xlsm' : 'Microsoft/',
    '.xlsx' : 'Microsoft/',
    '.doc' : 'Microsoft/',
    '.docx' : 'Microsoft/',
    #pdf
    '.pdf' : 'PDFs/',
    #text
    '.txt' : 'TxtFiles/',
    '.rtf' : 'TxtFiles/',
    #video
    '.3gp' : 'Videos/',
    '.3g2' : 'Videos/',
    '.avi' : 'Videos/',
    '.mkv' : 'Videos/',
    '.m4v' : 'Videos/',
    '.mp4' : 'Videos/',
    '.mov' : 'Videos/',
    '.wmv' : 'Videos/',
    '.vob' : 'Videos/',
    '.rm' : 'Videos/',
    '.mpg' : 'Videos/',
    '.mpeg' : 'Videos/',
    '.flv' : 'Videos/',
    '.swf' : 'Videos/',

}

all_extension_windows ={
    #other
    'other' : 'Others',
    #audio
    '.mp3' : 'Audio\\',
    '.cda' : 'Audio\\',
    '.mid' : 'Audio\\',
    '.midi' : 'Audio\\',
    'ogg' : 'Audio\\',
    '.wav' : 'Audio\\',
    'wma' : 'Audio\\',
    'wpl' : 'Audio\\',
    #image
    '.png' : 'Images\\',
    '.ai' : 'Images\\',
    '.gif' : 'Images\\',
    '.ico' : 'Images\\',
    '.jpeg' : 'Images\\',
    '.jpg' : 'Images\\',
    '.psd' : 'Images\\',
    '.svg' : 'Images\\',
    '.tif' : 'Images\\',
    '.bmp' : 'Images\\',
    #zip
    '.7z' : 'ZipFiles\\',
    '.arj' : 'ZipFiles\\',
    '.deb' : 'ZipFile\\',
    '.pkg' : 'ZipFiles\\',
    '.rar' : 'ZipFiles\\',
    '.rpm' : 'ZipFiles\\',
    '.tar.gz' : 'ZipFiles\\',
    '.z' : 'ZipFiles\\',
    '.zip' : 'ZipFiles\\',
    #executable
    '.apk' : 'Executable\\',
    '.bat' : 'Executable\\',
    '.bin' : 'Executable\\',
    '.com' : 'Executable\\',
    '.exe' : 'Executable\\',
    '.jar' : 'Executable\\',
    '.gadget' : 'Executable\\',
    '.msi' : 'Executable\\',
    '.wsf' : 'Executable\\',
    '.cgi' : 'Executable\\',
    #microsoft
    '.ppt' : 'Microsoft\\',
    '.pptx' : 'Microsoft\\',
    '.pps' : 'Microsoft\\',
    '.xls' : 'Microsoft\\',
    '.xlsm' : 'Microsoft\\',
    '.xlsx' : 'Microsoft\\',
    '.doc' : 'Microsoft\\',
    '.docx' : 'Microsoft\\',
    #pdf
    '.pdf' : 'PDFs\\',
    #text
    '.txt' : 'TxtFiles\\',
    '.rtf' : 'TxtFiles\\',
    #video
    '.3gp' : 'Videos\\',
    '.3g2' : 'Videos\\',
    '.avi' : 'Videos\\',
    '.mkv' : 'Videos\\',
    '.m4v' : 'Videos\\',
    '.mp4' : 'Videos\\',
    '.mov' : 'Videos\\',
    '.wmv' : 'Videos\\',
    '.vob' : 'Videos\\',
    '.rm' : 'Videos\\',
    '.mpg' : 'Videos\\',
    '.mpeg' : 'Videos\\',
    '.flv' : 'Videos\\',
    '.swf' : 'Videos\\',

}